language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kaliayev/docker-ci -f Dockerfile.dev .

script:
  - docker run -e CI=true kaliayev/docker-ci npm run test -- --coverage
