FROM node:alpine

WORKDIR '/home/node'

COPY package.json .
RUN npm config set unsafe-perm true
RUN npm install --loglevel=warn

RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache

COPY . .

CMD ["npm", "run", "start"]